name = "CategoricalArrays"
uuid = "324d7699-5711-5eae-9e2f-1d82baa6b597"
version = "0.5.5"

[deps]
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
Future = "9fa8497b-333b-5362-9e8d-4d0656e87820"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Missings = "e1d29d7a-bbdc-5cf2-9ac0-f12de2c33e28"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
DataAPI = "9a962f9c-6df0-11e9-0e5d-c546b8b5ee8a"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
